version: '3.4'

networks:
  pet-project:
    name: pet-project-network

services:
  identityserver:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      CONNECTION_STRING: Server=postgres;Port=5432;Username=postgres;Password=password;Database=PetProject.IdentityServer
      SEQ_SERVER_URL: http://seq:80
    ports:
      - '5000:80'
      - '5001:443'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - pet-project

  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: QI3WfQs5d7fFLlK6zBqIXq9vD1+DxO4Axw4J7p+H+JmnybXbYPKrazX+zSqvHGTkeL36DRR1O8O6f26ghdhDUKdibo5oAPISBBlFG5a2LbQT
    ports:
      - '5341:80'
    networks:
      - pet-project

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - pet-project
    #ports:
    #  - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:6.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - pet-project
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json

  productapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      AUTH_SERVER: http://identityserver:80
      VALID_ISSUER: https://localhost:5001
      CONNECTION_STRING: mongodb://host.docker.internal:27017
      DATABASE_NAME: ProductApiDatabase
    ports:
      - '5002:80'
      - '5003:443'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - pet-project
