version: '3.4'

services:
  petproject.identityserver.host:
    image: ${DOCKER_REGISTRY-}petprojectidentityserverhost
    build:
      context: .
      dockerfile: src/PetProject.IdentityServer/src/PetProject.IdentityServer.Host/Dockerfile
