version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}petprojectidentityserverhost
    build:
      context: .
      dockerfile: src/PetProject.IdentityServer/src/PetProject.IdentityServer.Host/Dockerfile

  productapi:
    image: ${DOCKER_REGISTRY-}petprojectproductapihost
    build:
      context: .
      dockerfile: src/PetProject.ProductAPI/src/PetProject.ProductAPI.Host/Dockerfile

